---
- name: Manage WebSphere server script and logs
  hosts: ~ListOFServers~
  vars:
    log_dir: "/tmp/ansible_logs"
  pre_tasks:
    - name: Set log timestamp
      set_fact:
        log_timestamp: "{{ lookup('pipe', 'date +%d_%b_%Y_%H_%M_%S') }}"
    - name: Set log file
      set_fact:
        log_file: "{{ log_dir }}/{{ ansible_hostname }}_stop_{{ jvm_name }}_{{ log_timestamp }}.log"
  tasks:
    - name: Create logs directory on Ansible Host if it doesn't exist
      file:
        path: "{{ log_dir }}/"
        state: directory
      delegate_to: localhost

    - name: Create the directory on Inventory Hosts if it does not exist
      file:
        path: "{{ log_dir }}"
        state: directory
        mode: '0755'


    - name: Check for the existence of a PID file
      stat:
        path: "{{ profile_path }}/logs/{{ jvm_name }}/{{ jvm_name }}.pid"
      register: pid_file_status

    - name: Show a message and exit if PID file not found
      fail:
        msg: "The server {{ jvm_name }} is already stopped (PID file not found). Exiting..."
      when: not pid_file_status.stat.exists

    - name: Get the PID from the PID file
      command: "cat {{ profile_path }}/logs/{{ jvm_name }}/{{ jvm_name }}.pid"
      register: pid
      when: pid_file_status.stat.exists

    - name: Check if the server is running using PID
      shell: "ps -p {{ pid.stdout }} -o comm="
      register: server_status
      ignore_errors: yes
      when: pid_file_status.stat.exists

    - name: Show a message and exit if the server is stopped
      fail:
        msg: "The server {{ jvm_name }} is already stopped (process not running). Exiting..."
      when: server_status.rc != 0 and pid_file_status.stat.exists

    - name: Stop {{ jvm_name }}
      shell: |
        {
          echo "$(date '+%Y-%m-%d %H:%M:%S') : Stopping {{ jvm_name }}..."
          {{ profile_path }}/bin/stopServer.sh {{ jvm_name }}
          echo "Cleaning Up tmp/wstemp directories...."
          rm -rf {{ profile_path }}/temp/*
          rm -rf {{ profile_path }}/wstemp/*
          echo "$(date '+%Y-%m-%d %H:%M:%S') : Script execution is completed."
        } | tee "{{ log_file}}"
      register: script_output
      when: server_status.rc == 0 and pid_file_status.stat.exists

    - name: Show script output
      debug:
        msg: "{{ item }}"
      with_items: "{{ script_output.stdout.split('\n') }}"

    - name: Gather log files
      find:
        paths: "{{ log_dir }}"
        patterns: "*stop*.log"
      register: log_files
      no_log: true

    - name: Set initial latest_log_file
      set_fact:
        latest_log_file: "{{ log_files.files[0] }}"
      no_log: true

    - name: Get the latest log file
      set_fact:
        latest_log_file: "{{ item }}"
      when: item.mtime > latest_log_file.mtime
      with_items: "{{ log_files.files }}"
      no_log: true

    - name: Print the latest log file name
      debug:
        msg: "Latest log file: {{ latest_log_file.path }}"

    - name: Create logs directory if it doesn't exist
      file:
        path: "{{ log_dir }}/"
        state: directory
      run_once: yes
      delegate_to: localhost
      no_log: true

    - name: Copy the latest log file to the Ansible host
      fetch:
        src: "{{ latest_log_file.path }}"
        dest: "{{ log_dir }}/"
        flat: yes
      when: log_files.matched > 0
      run_once: yes

    - name: Remove logs except the latest 6
      shell: |
        find "{{ log_dir }}/" -type f -name '{{ ansible_hostname }}_stop_{{ jvm_name }}_*.log' -printf '%T@ %p\n' |
        sort -k1,1nr |
        awk 'NR>6 {print $2}' |
        xargs rm -f
      run_once: yes
      no_log: true